### ISSUE TITLE
Quality and Dependency tool integrations

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/TraceFit#12]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/TraceFit/issues/9
- [ ] https://github.com/Oztechan/TraceFit/issues/10
- [ ] https://github.com/Oztechan/TraceFit/issues/11
- [ ] Setup Sonarqube
- [ ] Setup Codecov
- [ ] https://github.com/Oztechan/TraceFit/issues/13
- [ ] https://github.com/Oztechan/TraceFit/issues/40
- [ ] https://github.com/Oztechan/TraceFit/issues/68
```
