### ISSUE TITLE
GitHub Action Integration

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/TraceFit#2]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/TraceFit/issues/6
- [ ] https://github.com/Oztechan/TraceFit/issues/8
- [ ] Setup CodeAnalysis job
- [ ] Setup UploadQualityReports job
- [ ] Setup Xcodebuild job
```
