### ISSUE TITLE
Update project structure

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/TraceFit#71]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/TraceFit/issues/70
- [ ] https://github.com/Oztechan/TraceFit/issues/75
- [ ] https://github.com/Oztechan/TraceFit/issues/72
```
